#!/bin/sh

CURDIR=`pwd`
	# requires inkscape and imagemagick to be installed
	if [ ! -x /usr/local/bin/convert ]; then 
		echo "ERROR: imagemagick not installed!" 
		false 
	fi
	if [ ! -x /usr/local/bin/inkscape ]; then 
		echo "ERROR: inkscape not installed!" 
		false 
	fi
	
	# create XDG compatible icons from SVG
	for i in 16 22 32 48 64 128; do 
		mkdir -p "icons/hicolor/${i}x${i}/apps" 
		inkscape --export-width=${i} \
			 --export-height=${i} \
			 --export-png="$CURDIR/icons/hicolor/${i}x${i}/apps/ghostbsd-irc.png" \
				$CURDIR/ghostbsd-irc.svg ; \
	done
	
	# create XPM icons for the debian menu system
	mkdir -p icons/pixmaps
	convert icons/hicolor/32x32/apps/ghostbsd-irc.png icons/pixmaps/ghostbsd-irc.xpm
	convert icons/hicolor/16x16/apps/ghostbsd-irc.png icons/pixmaps/ghostbsd-irc-16.xpm

	mkdir -p icons/hicolor/scalable
	cp $CURDIR/*.svg $CURDIR/icons/hicolor/scalable